// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fft2d_top.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fft2d_top::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<64> fft2d_top::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_logic fft2d_top::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> fft2d_top::ap_const_lv10_0 = "0000000000";
const sc_lv<10> fft2d_top::ap_const_lv10_1 = "1";
const sc_lv<64> fft2d_top::ap_const_lv64_1 = "1";

fft2d_top::fft2d_top(sc_module_name name) : sc_module(name), mVcdFile(0) {
    arr1_U = new fft2d_top_arr1("arr1_U");
    arr1_U->clk(ap_clk);
    arr1_U->reset(ap_rst_n_inv);
    arr1_U->i_address0(ap_var_for_const0);
    arr1_U->i_ce0(ap_var_for_const1);
    arr1_U->i_q0(arr1_i_q0);
    arr1_U->i_address1(Loop_l_transp_out_pr_U0_arr1_address1);
    arr1_U->i_ce1(Loop_l_transp_out_pr_U0_arr1_ce1);
    arr1_U->i_we1(Loop_l_transp_out_pr_U0_arr1_we1);
    arr1_U->i_d1(Loop_l_transp_out_pr_U0_arr1_d1);
    arr1_U->t_address0(Loop_l_wr_o_fifo_pro_U0_arr1_address0);
    arr1_U->t_ce0(Loop_l_wr_o_fifo_pro_U0_arr1_ce0);
    arr1_U->t_q0(arr1_t_q0);
    arr1_U->t_address1(ap_var_for_const0);
    arr1_U->t_ce1(ap_var_for_const1);
    arr1_U->t_we1(ap_var_for_const1);
    arr1_U->t_d1(ap_var_for_const2);
    arr1_U->i_ce(ap_var_for_const3);
    arr1_U->t_ce(ap_var_for_const3);
    arr1_U->i_full_n(arr1_i_full_n);
    arr1_U->i_write(Loop_l_transp_out_pr_U0_ap_done);
    arr1_U->t_empty_n(arr1_t_empty_n);
    arr1_U->t_read(Loop_l_wr_o_fifo_pro_U0_ap_ready);
    arr0_U = new fft2d_top_arr1("arr0_U");
    arr0_U->clk(ap_clk);
    arr0_U->reset(ap_rst_n_inv);
    arr0_U->i_address0(ap_var_for_const0);
    arr0_U->i_ce0(ap_var_for_const1);
    arr0_U->i_q0(arr0_i_q0);
    arr0_U->i_address1(Loop_l_transp_mid_pr_U0_arr0_address1);
    arr0_U->i_ce1(Loop_l_transp_mid_pr_U0_arr0_ce1);
    arr0_U->i_we1(Loop_l_transp_mid_pr_U0_arr0_we1);
    arr0_U->i_d1(Loop_l_transp_mid_pr_U0_arr0_d1);
    arr0_U->t_address0(Loop_l_f1d_col_proc2_U0_arr0_address0);
    arr0_U->t_ce0(Loop_l_f1d_col_proc2_U0_arr0_ce0);
    arr0_U->t_q0(arr0_t_q0);
    arr0_U->t_address1(ap_var_for_const0);
    arr0_U->t_ce1(ap_var_for_const1);
    arr0_U->t_we1(ap_var_for_const1);
    arr0_U->t_d1(ap_var_for_const2);
    arr0_U->i_ce(ap_var_for_const3);
    arr0_U->t_ce(ap_var_for_const3);
    arr0_U->i_full_n(arr0_i_full_n);
    arr0_U->i_write(Loop_l_transp_mid_pr_U0_ap_done);
    arr0_U->t_empty_n(arr0_t_empty_n);
    arr0_U->t_read(Loop_l_f1d_col_proc2_U0_ap_ready);
    Loop_l_rd_xn_proc23_U0 = new Loop_l_rd_xn_proc23("Loop_l_rd_xn_proc23_U0");
    Loop_l_rd_xn_proc23_U0->ap_clk(ap_clk);
    Loop_l_rd_xn_proc23_U0->ap_rst(ap_rst_n_inv);
    Loop_l_rd_xn_proc23_U0->ap_start(Loop_l_rd_xn_proc23_U0_ap_start);
    Loop_l_rd_xn_proc23_U0->start_full_n(start_for_Loop_l_f1d_row_proc2_U0_full_n);
    Loop_l_rd_xn_proc23_U0->ap_done(Loop_l_rd_xn_proc23_U0_ap_done);
    Loop_l_rd_xn_proc23_U0->ap_continue(Loop_l_rd_xn_proc23_U0_ap_continue);
    Loop_l_rd_xn_proc23_U0->ap_idle(Loop_l_rd_xn_proc23_U0_ap_idle);
    Loop_l_rd_xn_proc23_U0->ap_ready(Loop_l_rd_xn_proc23_U0_ap_ready);
    Loop_l_rd_xn_proc23_U0->start_out(Loop_l_rd_xn_proc23_U0_start_out);
    Loop_l_rd_xn_proc23_U0->start_write(Loop_l_rd_xn_proc23_U0_start_write);
    Loop_l_rd_xn_proc23_U0->xn_TDATA(xn_TDATA);
    Loop_l_rd_xn_proc23_U0->xn_TVALID(xn_TVALID);
    Loop_l_rd_xn_proc23_U0->xn_TREADY(Loop_l_rd_xn_proc23_U0_xn_TREADY);
    Loop_l_rd_xn_proc23_U0->xn_TLAST(Loop_l_rd_xn_proc23_U0_xn_TLAST);
    Loop_l_rd_xn_proc23_U0->xn_fifo_V_din(Loop_l_rd_xn_proc23_U0_xn_fifo_V_din);
    Loop_l_rd_xn_proc23_U0->xn_fifo_V_full_n(xn_fifo_V_full_n);
    Loop_l_rd_xn_proc23_U0->xn_fifo_V_write(Loop_l_rd_xn_proc23_U0_xn_fifo_V_write);
    Loop_l_f1d_row_proc2_U0 = new Loop_l_f1d_row_proc2("Loop_l_f1d_row_proc2_U0");
    Loop_l_f1d_row_proc2_U0->ap_clk(ap_clk);
    Loop_l_f1d_row_proc2_U0->ap_rst(ap_rst_n_inv);
    Loop_l_f1d_row_proc2_U0->ap_start(Loop_l_f1d_row_proc2_U0_ap_start);
    Loop_l_f1d_row_proc2_U0->start_full_n(start_for_Loop_l_transp_mid_pr_U0_full_n);
    Loop_l_f1d_row_proc2_U0->ap_done(Loop_l_f1d_row_proc2_U0_ap_done);
    Loop_l_f1d_row_proc2_U0->ap_continue(Loop_l_f1d_row_proc2_U0_ap_continue);
    Loop_l_f1d_row_proc2_U0->ap_idle(Loop_l_f1d_row_proc2_U0_ap_idle);
    Loop_l_f1d_row_proc2_U0->ap_ready(Loop_l_f1d_row_proc2_U0_ap_ready);
    Loop_l_f1d_row_proc2_U0->start_out(Loop_l_f1d_row_proc2_U0_start_out);
    Loop_l_f1d_row_proc2_U0->start_write(Loop_l_f1d_row_proc2_U0_start_write);
    Loop_l_f1d_row_proc2_U0->xk_mid_row_fifo_V_din(Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_din);
    Loop_l_f1d_row_proc2_U0->xk_mid_row_fifo_V_full_n(xk_mid_row_fifo_V_full_n);
    Loop_l_f1d_row_proc2_U0->xk_mid_row_fifo_V_write(Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_write);
    Loop_l_f1d_row_proc2_U0->xn_fifo_V_dout(xn_fifo_V_dout);
    Loop_l_f1d_row_proc2_U0->xn_fifo_V_empty_n(xn_fifo_V_empty_n);
    Loop_l_f1d_row_proc2_U0->xn_fifo_V_read(Loop_l_f1d_row_proc2_U0_xn_fifo_V_read);
    Loop_l_transp_mid_pr_U0 = new Loop_l_transp_mid_pr("Loop_l_transp_mid_pr_U0");
    Loop_l_transp_mid_pr_U0->ap_clk(ap_clk);
    Loop_l_transp_mid_pr_U0->ap_rst(ap_rst_n_inv);
    Loop_l_transp_mid_pr_U0->ap_start(Loop_l_transp_mid_pr_U0_ap_start);
    Loop_l_transp_mid_pr_U0->ap_done(Loop_l_transp_mid_pr_U0_ap_done);
    Loop_l_transp_mid_pr_U0->ap_continue(Loop_l_transp_mid_pr_U0_ap_continue);
    Loop_l_transp_mid_pr_U0->ap_idle(Loop_l_transp_mid_pr_U0_ap_idle);
    Loop_l_transp_mid_pr_U0->ap_ready(Loop_l_transp_mid_pr_U0_ap_ready);
    Loop_l_transp_mid_pr_U0->xk_mid_row_fifo_V_dout(xk_mid_row_fifo_V_dout);
    Loop_l_transp_mid_pr_U0->xk_mid_row_fifo_V_empty_n(xk_mid_row_fifo_V_empty_n);
    Loop_l_transp_mid_pr_U0->xk_mid_row_fifo_V_read(Loop_l_transp_mid_pr_U0_xk_mid_row_fifo_V_read);
    Loop_l_transp_mid_pr_U0->arr0_address1(Loop_l_transp_mid_pr_U0_arr0_address1);
    Loop_l_transp_mid_pr_U0->arr0_ce1(Loop_l_transp_mid_pr_U0_arr0_ce1);
    Loop_l_transp_mid_pr_U0->arr0_we1(Loop_l_transp_mid_pr_U0_arr0_we1);
    Loop_l_transp_mid_pr_U0->arr0_d1(Loop_l_transp_mid_pr_U0_arr0_d1);
    Loop_l_f1d_col_proc2_U0 = new Loop_l_f1d_col_proc2("Loop_l_f1d_col_proc2_U0");
    Loop_l_f1d_col_proc2_U0->ap_clk(ap_clk);
    Loop_l_f1d_col_proc2_U0->ap_rst(ap_rst_n_inv);
    Loop_l_f1d_col_proc2_U0->ap_start(Loop_l_f1d_col_proc2_U0_ap_start);
    Loop_l_f1d_col_proc2_U0->start_full_n(start_for_Loop_l_transp_out_pr_U0_full_n);
    Loop_l_f1d_col_proc2_U0->ap_done(Loop_l_f1d_col_proc2_U0_ap_done);
    Loop_l_f1d_col_proc2_U0->ap_continue(Loop_l_f1d_col_proc2_U0_ap_continue);
    Loop_l_f1d_col_proc2_U0->ap_idle(Loop_l_f1d_col_proc2_U0_ap_idle);
    Loop_l_f1d_col_proc2_U0->ap_ready(Loop_l_f1d_col_proc2_U0_ap_ready);
    Loop_l_f1d_col_proc2_U0->start_out(Loop_l_f1d_col_proc2_U0_start_out);
    Loop_l_f1d_col_proc2_U0->start_write(Loop_l_f1d_col_proc2_U0_start_write);
    Loop_l_f1d_col_proc2_U0->xk_mid_col_fifo_V_din(Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_din);
    Loop_l_f1d_col_proc2_U0->xk_mid_col_fifo_V_full_n(xk_mid_col_fifo_V_full_n);
    Loop_l_f1d_col_proc2_U0->xk_mid_col_fifo_V_write(Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_write);
    Loop_l_f1d_col_proc2_U0->arr0_address0(Loop_l_f1d_col_proc2_U0_arr0_address0);
    Loop_l_f1d_col_proc2_U0->arr0_ce0(Loop_l_f1d_col_proc2_U0_arr0_ce0);
    Loop_l_f1d_col_proc2_U0->arr0_q0(arr0_t_q0);
    Loop_l_transp_out_pr_U0 = new Loop_l_transp_out_pr("Loop_l_transp_out_pr_U0");
    Loop_l_transp_out_pr_U0->ap_clk(ap_clk);
    Loop_l_transp_out_pr_U0->ap_rst(ap_rst_n_inv);
    Loop_l_transp_out_pr_U0->ap_start(Loop_l_transp_out_pr_U0_ap_start);
    Loop_l_transp_out_pr_U0->ap_done(Loop_l_transp_out_pr_U0_ap_done);
    Loop_l_transp_out_pr_U0->ap_continue(Loop_l_transp_out_pr_U0_ap_continue);
    Loop_l_transp_out_pr_U0->ap_idle(Loop_l_transp_out_pr_U0_ap_idle);
    Loop_l_transp_out_pr_U0->ap_ready(Loop_l_transp_out_pr_U0_ap_ready);
    Loop_l_transp_out_pr_U0->xk_mid_col_fifo_V_dout(xk_mid_col_fifo_V_dout);
    Loop_l_transp_out_pr_U0->xk_mid_col_fifo_V_empty_n(xk_mid_col_fifo_V_empty_n);
    Loop_l_transp_out_pr_U0->xk_mid_col_fifo_V_read(Loop_l_transp_out_pr_U0_xk_mid_col_fifo_V_read);
    Loop_l_transp_out_pr_U0->arr1_address1(Loop_l_transp_out_pr_U0_arr1_address1);
    Loop_l_transp_out_pr_U0->arr1_ce1(Loop_l_transp_out_pr_U0_arr1_ce1);
    Loop_l_transp_out_pr_U0->arr1_we1(Loop_l_transp_out_pr_U0_arr1_we1);
    Loop_l_transp_out_pr_U0->arr1_d1(Loop_l_transp_out_pr_U0_arr1_d1);
    Loop_l_wr_o_fifo_pro_U0 = new Loop_l_wr_o_fifo_pro("Loop_l_wr_o_fifo_pro_U0");
    Loop_l_wr_o_fifo_pro_U0->ap_clk(ap_clk);
    Loop_l_wr_o_fifo_pro_U0->ap_rst(ap_rst_n_inv);
    Loop_l_wr_o_fifo_pro_U0->ap_start(Loop_l_wr_o_fifo_pro_U0_ap_start);
    Loop_l_wr_o_fifo_pro_U0->start_full_n(start_for_Loop_l_wr_xk_proc29_U0_full_n);
    Loop_l_wr_o_fifo_pro_U0->ap_done(Loop_l_wr_o_fifo_pro_U0_ap_done);
    Loop_l_wr_o_fifo_pro_U0->ap_continue(Loop_l_wr_o_fifo_pro_U0_ap_continue);
    Loop_l_wr_o_fifo_pro_U0->ap_idle(Loop_l_wr_o_fifo_pro_U0_ap_idle);
    Loop_l_wr_o_fifo_pro_U0->ap_ready(Loop_l_wr_o_fifo_pro_U0_ap_ready);
    Loop_l_wr_o_fifo_pro_U0->start_out(Loop_l_wr_o_fifo_pro_U0_start_out);
    Loop_l_wr_o_fifo_pro_U0->start_write(Loop_l_wr_o_fifo_pro_U0_start_write);
    Loop_l_wr_o_fifo_pro_U0->arr1_address0(Loop_l_wr_o_fifo_pro_U0_arr1_address0);
    Loop_l_wr_o_fifo_pro_U0->arr1_ce0(Loop_l_wr_o_fifo_pro_U0_arr1_ce0);
    Loop_l_wr_o_fifo_pro_U0->arr1_q0(arr1_t_q0);
    Loop_l_wr_o_fifo_pro_U0->xk_fifo_V_din(Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_din);
    Loop_l_wr_o_fifo_pro_U0->xk_fifo_V_full_n(xk_fifo_V_full_n);
    Loop_l_wr_o_fifo_pro_U0->xk_fifo_V_write(Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_write);
    Loop_l_wr_xk_proc29_U0 = new Loop_l_wr_xk_proc29("Loop_l_wr_xk_proc29_U0");
    Loop_l_wr_xk_proc29_U0->ap_clk(ap_clk);
    Loop_l_wr_xk_proc29_U0->ap_rst(ap_rst_n_inv);
    Loop_l_wr_xk_proc29_U0->ap_start(Loop_l_wr_xk_proc29_U0_ap_start);
    Loop_l_wr_xk_proc29_U0->ap_done(Loop_l_wr_xk_proc29_U0_ap_done);
    Loop_l_wr_xk_proc29_U0->ap_continue(Loop_l_wr_xk_proc29_U0_ap_continue);
    Loop_l_wr_xk_proc29_U0->ap_idle(Loop_l_wr_xk_proc29_U0_ap_idle);
    Loop_l_wr_xk_proc29_U0->ap_ready(Loop_l_wr_xk_proc29_U0_ap_ready);
    Loop_l_wr_xk_proc29_U0->xk_fifo_V_dout(xk_fifo_V_dout);
    Loop_l_wr_xk_proc29_U0->xk_fifo_V_empty_n(xk_fifo_V_empty_n);
    Loop_l_wr_xk_proc29_U0->xk_fifo_V_read(Loop_l_wr_xk_proc29_U0_xk_fifo_V_read);
    Loop_l_wr_xk_proc29_U0->xk_TDATA(Loop_l_wr_xk_proc29_U0_xk_TDATA);
    Loop_l_wr_xk_proc29_U0->xk_TVALID(Loop_l_wr_xk_proc29_U0_xk_TVALID);
    Loop_l_wr_xk_proc29_U0->xk_TREADY(xk_TREADY);
    Loop_l_wr_xk_proc29_U0->xk_TLAST(Loop_l_wr_xk_proc29_U0_xk_TLAST);
    xn_fifo_V_U = new fifo_w64_d32_A_x2("xn_fifo_V_U");
    xn_fifo_V_U->clk(ap_clk);
    xn_fifo_V_U->reset(ap_rst_n_inv);
    xn_fifo_V_U->if_read_ce(ap_var_for_const3);
    xn_fifo_V_U->if_write_ce(ap_var_for_const3);
    xn_fifo_V_U->if_din(Loop_l_rd_xn_proc23_U0_xn_fifo_V_din);
    xn_fifo_V_U->if_full_n(xn_fifo_V_full_n);
    xn_fifo_V_U->if_write(Loop_l_rd_xn_proc23_U0_xn_fifo_V_write);
    xn_fifo_V_U->if_dout(xn_fifo_V_dout);
    xn_fifo_V_U->if_empty_n(xn_fifo_V_empty_n);
    xn_fifo_V_U->if_read(Loop_l_f1d_row_proc2_U0_xn_fifo_V_read);
    xk_mid_row_fifo_V_U = new fifo_w64_d32_A_x2("xk_mid_row_fifo_V_U");
    xk_mid_row_fifo_V_U->clk(ap_clk);
    xk_mid_row_fifo_V_U->reset(ap_rst_n_inv);
    xk_mid_row_fifo_V_U->if_read_ce(ap_var_for_const3);
    xk_mid_row_fifo_V_U->if_write_ce(ap_var_for_const3);
    xk_mid_row_fifo_V_U->if_din(Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_din);
    xk_mid_row_fifo_V_U->if_full_n(xk_mid_row_fifo_V_full_n);
    xk_mid_row_fifo_V_U->if_write(Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_write);
    xk_mid_row_fifo_V_U->if_dout(xk_mid_row_fifo_V_dout);
    xk_mid_row_fifo_V_U->if_empty_n(xk_mid_row_fifo_V_empty_n);
    xk_mid_row_fifo_V_U->if_read(Loop_l_transp_mid_pr_U0_xk_mid_row_fifo_V_read);
    xk_mid_col_fifo_V_U = new fifo_w64_d32_A_x2("xk_mid_col_fifo_V_U");
    xk_mid_col_fifo_V_U->clk(ap_clk);
    xk_mid_col_fifo_V_U->reset(ap_rst_n_inv);
    xk_mid_col_fifo_V_U->if_read_ce(ap_var_for_const3);
    xk_mid_col_fifo_V_U->if_write_ce(ap_var_for_const3);
    xk_mid_col_fifo_V_U->if_din(Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_din);
    xk_mid_col_fifo_V_U->if_full_n(xk_mid_col_fifo_V_full_n);
    xk_mid_col_fifo_V_U->if_write(Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_write);
    xk_mid_col_fifo_V_U->if_dout(xk_mid_col_fifo_V_dout);
    xk_mid_col_fifo_V_U->if_empty_n(xk_mid_col_fifo_V_empty_n);
    xk_mid_col_fifo_V_U->if_read(Loop_l_transp_out_pr_U0_xk_mid_col_fifo_V_read);
    xk_fifo_V_U = new fifo_w64_d32_A_x2("xk_fifo_V_U");
    xk_fifo_V_U->clk(ap_clk);
    xk_fifo_V_U->reset(ap_rst_n_inv);
    xk_fifo_V_U->if_read_ce(ap_var_for_const3);
    xk_fifo_V_U->if_write_ce(ap_var_for_const3);
    xk_fifo_V_U->if_din(Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_din);
    xk_fifo_V_U->if_full_n(xk_fifo_V_full_n);
    xk_fifo_V_U->if_write(Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_write);
    xk_fifo_V_U->if_dout(xk_fifo_V_dout);
    xk_fifo_V_U->if_empty_n(xk_fifo_V_empty_n);
    xk_fifo_V_U->if_read(Loop_l_wr_xk_proc29_U0_xk_fifo_V_read);
    start_for_Loop_l_f1d_row_proc2_U0_U = new start_for_Loop_l_f1d_row_proc2_U0("start_for_Loop_l_f1d_row_proc2_U0_U");
    start_for_Loop_l_f1d_row_proc2_U0_U->clk(ap_clk);
    start_for_Loop_l_f1d_row_proc2_U0_U->reset(ap_rst_n_inv);
    start_for_Loop_l_f1d_row_proc2_U0_U->if_read_ce(ap_var_for_const3);
    start_for_Loop_l_f1d_row_proc2_U0_U->if_write_ce(ap_var_for_const3);
    start_for_Loop_l_f1d_row_proc2_U0_U->if_din(start_for_Loop_l_f1d_row_proc2_U0_din);
    start_for_Loop_l_f1d_row_proc2_U0_U->if_full_n(start_for_Loop_l_f1d_row_proc2_U0_full_n);
    start_for_Loop_l_f1d_row_proc2_U0_U->if_write(Loop_l_rd_xn_proc23_U0_start_write);
    start_for_Loop_l_f1d_row_proc2_U0_U->if_dout(start_for_Loop_l_f1d_row_proc2_U0_dout);
    start_for_Loop_l_f1d_row_proc2_U0_U->if_empty_n(start_for_Loop_l_f1d_row_proc2_U0_empty_n);
    start_for_Loop_l_f1d_row_proc2_U0_U->if_read(Loop_l_f1d_row_proc2_U0_ap_ready);
    start_for_Loop_l_transp_mid_pr_U0_U = new start_for_Loop_l_transp_mid_pr_U0("start_for_Loop_l_transp_mid_pr_U0_U");
    start_for_Loop_l_transp_mid_pr_U0_U->clk(ap_clk);
    start_for_Loop_l_transp_mid_pr_U0_U->reset(ap_rst_n_inv);
    start_for_Loop_l_transp_mid_pr_U0_U->if_read_ce(ap_var_for_const3);
    start_for_Loop_l_transp_mid_pr_U0_U->if_write_ce(ap_var_for_const3);
    start_for_Loop_l_transp_mid_pr_U0_U->if_din(start_for_Loop_l_transp_mid_pr_U0_din);
    start_for_Loop_l_transp_mid_pr_U0_U->if_full_n(start_for_Loop_l_transp_mid_pr_U0_full_n);
    start_for_Loop_l_transp_mid_pr_U0_U->if_write(Loop_l_f1d_row_proc2_U0_start_write);
    start_for_Loop_l_transp_mid_pr_U0_U->if_dout(start_for_Loop_l_transp_mid_pr_U0_dout);
    start_for_Loop_l_transp_mid_pr_U0_U->if_empty_n(start_for_Loop_l_transp_mid_pr_U0_empty_n);
    start_for_Loop_l_transp_mid_pr_U0_U->if_read(Loop_l_transp_mid_pr_U0_ap_ready);
    start_for_Loop_l_transp_out_pr_U0_U = new start_for_Loop_l_transp_out_pr_U0("start_for_Loop_l_transp_out_pr_U0_U");
    start_for_Loop_l_transp_out_pr_U0_U->clk(ap_clk);
    start_for_Loop_l_transp_out_pr_U0_U->reset(ap_rst_n_inv);
    start_for_Loop_l_transp_out_pr_U0_U->if_read_ce(ap_var_for_const3);
    start_for_Loop_l_transp_out_pr_U0_U->if_write_ce(ap_var_for_const3);
    start_for_Loop_l_transp_out_pr_U0_U->if_din(start_for_Loop_l_transp_out_pr_U0_din);
    start_for_Loop_l_transp_out_pr_U0_U->if_full_n(start_for_Loop_l_transp_out_pr_U0_full_n);
    start_for_Loop_l_transp_out_pr_U0_U->if_write(Loop_l_f1d_col_proc2_U0_start_write);
    start_for_Loop_l_transp_out_pr_U0_U->if_dout(start_for_Loop_l_transp_out_pr_U0_dout);
    start_for_Loop_l_transp_out_pr_U0_U->if_empty_n(start_for_Loop_l_transp_out_pr_U0_empty_n);
    start_for_Loop_l_transp_out_pr_U0_U->if_read(Loop_l_transp_out_pr_U0_ap_ready);
    start_for_Loop_l_wr_xk_proc29_U0_U = new start_for_Loop_l_wr_xk_proc29_U0("start_for_Loop_l_wr_xk_proc29_U0_U");
    start_for_Loop_l_wr_xk_proc29_U0_U->clk(ap_clk);
    start_for_Loop_l_wr_xk_proc29_U0_U->reset(ap_rst_n_inv);
    start_for_Loop_l_wr_xk_proc29_U0_U->if_read_ce(ap_var_for_const3);
    start_for_Loop_l_wr_xk_proc29_U0_U->if_write_ce(ap_var_for_const3);
    start_for_Loop_l_wr_xk_proc29_U0_U->if_din(start_for_Loop_l_wr_xk_proc29_U0_din);
    start_for_Loop_l_wr_xk_proc29_U0_U->if_full_n(start_for_Loop_l_wr_xk_proc29_U0_full_n);
    start_for_Loop_l_wr_xk_proc29_U0_U->if_write(Loop_l_wr_o_fifo_pro_U0_start_write);
    start_for_Loop_l_wr_xk_proc29_U0_U->if_dout(start_for_Loop_l_wr_xk_proc29_U0_dout);
    start_for_Loop_l_wr_xk_proc29_U0_U->if_empty_n(start_for_Loop_l_wr_xk_proc29_U0_empty_n);
    start_for_Loop_l_wr_xk_proc29_U0_U->if_read(Loop_l_wr_xk_proc29_U0_ap_ready);

    SC_METHOD(thread_Loop_l_f1d_col_proc2_U0_ap_continue);

    SC_METHOD(thread_Loop_l_f1d_col_proc2_U0_ap_start);
    sensitive << ( arr0_t_empty_n );

    SC_METHOD(thread_Loop_l_f1d_row_proc2_U0_ap_continue);

    SC_METHOD(thread_Loop_l_f1d_row_proc2_U0_ap_start);
    sensitive << ( start_for_Loop_l_f1d_row_proc2_U0_empty_n );

    SC_METHOD(thread_Loop_l_rd_xn_proc23_U0_ap_continue);

    SC_METHOD(thread_Loop_l_rd_xn_proc23_U0_ap_start);

    SC_METHOD(thread_Loop_l_rd_xn_proc23_U0_xn_TLAST);
    sensitive << ( xn_TLAST );

    SC_METHOD(thread_Loop_l_transp_mid_pr_U0_ap_continue);
    sensitive << ( arr0_i_full_n );

    SC_METHOD(thread_Loop_l_transp_mid_pr_U0_ap_start);
    sensitive << ( start_for_Loop_l_transp_mid_pr_U0_empty_n );

    SC_METHOD(thread_Loop_l_transp_mid_pr_U0_arr0_full_n);
    sensitive << ( arr0_i_full_n );

    SC_METHOD(thread_Loop_l_transp_mid_pr_U0_start_full_n);

    SC_METHOD(thread_Loop_l_transp_mid_pr_U0_start_write);

    SC_METHOD(thread_Loop_l_transp_out_pr_U0_ap_continue);
    sensitive << ( arr1_i_full_n );

    SC_METHOD(thread_Loop_l_transp_out_pr_U0_ap_start);
    sensitive << ( start_for_Loop_l_transp_out_pr_U0_empty_n );

    SC_METHOD(thread_Loop_l_transp_out_pr_U0_arr1_full_n);
    sensitive << ( arr1_i_full_n );

    SC_METHOD(thread_Loop_l_transp_out_pr_U0_start_full_n);

    SC_METHOD(thread_Loop_l_transp_out_pr_U0_start_write);

    SC_METHOD(thread_Loop_l_wr_o_fifo_pro_U0_ap_continue);

    SC_METHOD(thread_Loop_l_wr_o_fifo_pro_U0_ap_start);
    sensitive << ( arr1_t_empty_n );

    SC_METHOD(thread_Loop_l_wr_xk_proc29_U0_ap_continue);

    SC_METHOD(thread_Loop_l_wr_xk_proc29_U0_ap_start);
    sensitive << ( start_for_Loop_l_wr_xk_proc29_U0_empty_n );

    SC_METHOD(thread_Loop_l_wr_xk_proc29_U0_start_full_n);

    SC_METHOD(thread_Loop_l_wr_xk_proc29_U0_start_write);

    SC_METHOD(thread_ap_channel_done_arr0);
    sensitive << ( Loop_l_transp_mid_pr_U0_ap_done );

    SC_METHOD(thread_ap_channel_done_arr1);
    sensitive << ( Loop_l_transp_out_pr_U0_ap_done );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_arr0_t_d0);

    SC_METHOD(thread_arr0_t_we0);

    SC_METHOD(thread_arr1_t_d0);

    SC_METHOD(thread_arr1_t_we0);

    SC_METHOD(thread_start_for_Loop_l_f1d_row_proc2_U0_din);

    SC_METHOD(thread_start_for_Loop_l_transp_mid_pr_U0_din);

    SC_METHOD(thread_start_for_Loop_l_transp_out_pr_U0_din);

    SC_METHOD(thread_start_for_Loop_l_wr_xk_proc29_U0_din);

    SC_METHOD(thread_xk_TDATA);
    sensitive << ( Loop_l_wr_xk_proc29_U0_xk_TDATA );

    SC_METHOD(thread_xk_TLAST);
    sensitive << ( Loop_l_wr_xk_proc29_U0_xk_TLAST );

    SC_METHOD(thread_xk_TVALID);
    sensitive << ( Loop_l_wr_xk_proc29_U0_xk_TVALID );

    SC_METHOD(thread_xn_TREADY);
    sensitive << ( Loop_l_rd_xn_proc23_U0_xn_TREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fft2d_top_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, xn_TDATA, "(port)xn_TDATA");
    sc_trace(mVcdFile, xn_TLAST, "(port)xn_TLAST");
    sc_trace(mVcdFile, xk_TDATA, "(port)xk_TDATA");
    sc_trace(mVcdFile, xk_TLAST, "(port)xk_TLAST");
    sc_trace(mVcdFile, xn_TVALID, "(port)xn_TVALID");
    sc_trace(mVcdFile, xn_TREADY, "(port)xn_TREADY");
    sc_trace(mVcdFile, xk_TVALID, "(port)xk_TVALID");
    sc_trace(mVcdFile, xk_TREADY, "(port)xk_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, arr1_i_q0, "arr1_i_q0");
    sc_trace(mVcdFile, arr1_t_q0, "arr1_t_q0");
    sc_trace(mVcdFile, arr0_i_q0, "arr0_i_q0");
    sc_trace(mVcdFile, arr0_t_q0, "arr0_t_q0");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_ap_start, "Loop_l_rd_xn_proc23_U0_ap_start");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_ap_done, "Loop_l_rd_xn_proc23_U0_ap_done");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_ap_continue, "Loop_l_rd_xn_proc23_U0_ap_continue");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_ap_idle, "Loop_l_rd_xn_proc23_U0_ap_idle");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_ap_ready, "Loop_l_rd_xn_proc23_U0_ap_ready");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_start_out, "Loop_l_rd_xn_proc23_U0_start_out");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_start_write, "Loop_l_rd_xn_proc23_U0_start_write");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_xn_TREADY, "Loop_l_rd_xn_proc23_U0_xn_TREADY");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_xn_TLAST, "Loop_l_rd_xn_proc23_U0_xn_TLAST");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_xn_fifo_V_din, "Loop_l_rd_xn_proc23_U0_xn_fifo_V_din");
    sc_trace(mVcdFile, Loop_l_rd_xn_proc23_U0_xn_fifo_V_write, "Loop_l_rd_xn_proc23_U0_xn_fifo_V_write");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_ap_start, "Loop_l_f1d_row_proc2_U0_ap_start");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_ap_done, "Loop_l_f1d_row_proc2_U0_ap_done");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_ap_continue, "Loop_l_f1d_row_proc2_U0_ap_continue");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_ap_idle, "Loop_l_f1d_row_proc2_U0_ap_idle");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_ap_ready, "Loop_l_f1d_row_proc2_U0_ap_ready");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_start_out, "Loop_l_f1d_row_proc2_U0_start_out");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_start_write, "Loop_l_f1d_row_proc2_U0_start_write");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_din, "Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_din");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_write, "Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_write");
    sc_trace(mVcdFile, Loop_l_f1d_row_proc2_U0_xn_fifo_V_read, "Loop_l_f1d_row_proc2_U0_xn_fifo_V_read");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_ap_start, "Loop_l_transp_mid_pr_U0_ap_start");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_ap_done, "Loop_l_transp_mid_pr_U0_ap_done");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_ap_continue, "Loop_l_transp_mid_pr_U0_ap_continue");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_ap_idle, "Loop_l_transp_mid_pr_U0_ap_idle");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_ap_ready, "Loop_l_transp_mid_pr_U0_ap_ready");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_xk_mid_row_fifo_V_read, "Loop_l_transp_mid_pr_U0_xk_mid_row_fifo_V_read");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_arr0_address1, "Loop_l_transp_mid_pr_U0_arr0_address1");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_arr0_ce1, "Loop_l_transp_mid_pr_U0_arr0_ce1");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_arr0_we1, "Loop_l_transp_mid_pr_U0_arr0_we1");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_arr0_d1, "Loop_l_transp_mid_pr_U0_arr0_d1");
    sc_trace(mVcdFile, ap_channel_done_arr0, "ap_channel_done_arr0");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_arr0_full_n, "Loop_l_transp_mid_pr_U0_arr0_full_n");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_ap_start, "Loop_l_f1d_col_proc2_U0_ap_start");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_ap_done, "Loop_l_f1d_col_proc2_U0_ap_done");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_ap_continue, "Loop_l_f1d_col_proc2_U0_ap_continue");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_ap_idle, "Loop_l_f1d_col_proc2_U0_ap_idle");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_ap_ready, "Loop_l_f1d_col_proc2_U0_ap_ready");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_start_out, "Loop_l_f1d_col_proc2_U0_start_out");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_start_write, "Loop_l_f1d_col_proc2_U0_start_write");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_din, "Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_din");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_write, "Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_write");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_arr0_address0, "Loop_l_f1d_col_proc2_U0_arr0_address0");
    sc_trace(mVcdFile, Loop_l_f1d_col_proc2_U0_arr0_ce0, "Loop_l_f1d_col_proc2_U0_arr0_ce0");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_ap_start, "Loop_l_transp_out_pr_U0_ap_start");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_ap_done, "Loop_l_transp_out_pr_U0_ap_done");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_ap_continue, "Loop_l_transp_out_pr_U0_ap_continue");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_ap_idle, "Loop_l_transp_out_pr_U0_ap_idle");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_ap_ready, "Loop_l_transp_out_pr_U0_ap_ready");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_xk_mid_col_fifo_V_read, "Loop_l_transp_out_pr_U0_xk_mid_col_fifo_V_read");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_arr1_address1, "Loop_l_transp_out_pr_U0_arr1_address1");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_arr1_ce1, "Loop_l_transp_out_pr_U0_arr1_ce1");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_arr1_we1, "Loop_l_transp_out_pr_U0_arr1_we1");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_arr1_d1, "Loop_l_transp_out_pr_U0_arr1_d1");
    sc_trace(mVcdFile, ap_channel_done_arr1, "ap_channel_done_arr1");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_arr1_full_n, "Loop_l_transp_out_pr_U0_arr1_full_n");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_ap_start, "Loop_l_wr_o_fifo_pro_U0_ap_start");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_ap_done, "Loop_l_wr_o_fifo_pro_U0_ap_done");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_ap_continue, "Loop_l_wr_o_fifo_pro_U0_ap_continue");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_ap_idle, "Loop_l_wr_o_fifo_pro_U0_ap_idle");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_ap_ready, "Loop_l_wr_o_fifo_pro_U0_ap_ready");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_start_out, "Loop_l_wr_o_fifo_pro_U0_start_out");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_start_write, "Loop_l_wr_o_fifo_pro_U0_start_write");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_arr1_address0, "Loop_l_wr_o_fifo_pro_U0_arr1_address0");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_arr1_ce0, "Loop_l_wr_o_fifo_pro_U0_arr1_ce0");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_din, "Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_din");
    sc_trace(mVcdFile, Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_write, "Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_write");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_ap_start, "Loop_l_wr_xk_proc29_U0_ap_start");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_ap_done, "Loop_l_wr_xk_proc29_U0_ap_done");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_ap_continue, "Loop_l_wr_xk_proc29_U0_ap_continue");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_ap_idle, "Loop_l_wr_xk_proc29_U0_ap_idle");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_ap_ready, "Loop_l_wr_xk_proc29_U0_ap_ready");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_xk_fifo_V_read, "Loop_l_wr_xk_proc29_U0_xk_fifo_V_read");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_xk_TDATA, "Loop_l_wr_xk_proc29_U0_xk_TDATA");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_xk_TVALID, "Loop_l_wr_xk_proc29_U0_xk_TVALID");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_xk_TLAST, "Loop_l_wr_xk_proc29_U0_xk_TLAST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, arr0_i_full_n, "arr0_i_full_n");
    sc_trace(mVcdFile, arr0_t_empty_n, "arr0_t_empty_n");
    sc_trace(mVcdFile, arr0_t_d0, "arr0_t_d0");
    sc_trace(mVcdFile, arr0_t_we0, "arr0_t_we0");
    sc_trace(mVcdFile, arr1_i_full_n, "arr1_i_full_n");
    sc_trace(mVcdFile, arr1_t_empty_n, "arr1_t_empty_n");
    sc_trace(mVcdFile, arr1_t_d0, "arr1_t_d0");
    sc_trace(mVcdFile, arr1_t_we0, "arr1_t_we0");
    sc_trace(mVcdFile, xn_fifo_V_full_n, "xn_fifo_V_full_n");
    sc_trace(mVcdFile, xn_fifo_V_dout, "xn_fifo_V_dout");
    sc_trace(mVcdFile, xn_fifo_V_empty_n, "xn_fifo_V_empty_n");
    sc_trace(mVcdFile, xk_mid_row_fifo_V_full_n, "xk_mid_row_fifo_V_full_n");
    sc_trace(mVcdFile, xk_mid_row_fifo_V_dout, "xk_mid_row_fifo_V_dout");
    sc_trace(mVcdFile, xk_mid_row_fifo_V_empty_n, "xk_mid_row_fifo_V_empty_n");
    sc_trace(mVcdFile, xk_mid_col_fifo_V_full_n, "xk_mid_col_fifo_V_full_n");
    sc_trace(mVcdFile, xk_mid_col_fifo_V_dout, "xk_mid_col_fifo_V_dout");
    sc_trace(mVcdFile, xk_mid_col_fifo_V_empty_n, "xk_mid_col_fifo_V_empty_n");
    sc_trace(mVcdFile, xk_fifo_V_full_n, "xk_fifo_V_full_n");
    sc_trace(mVcdFile, xk_fifo_V_dout, "xk_fifo_V_dout");
    sc_trace(mVcdFile, xk_fifo_V_empty_n, "xk_fifo_V_empty_n");
    sc_trace(mVcdFile, start_for_Loop_l_f1d_row_proc2_U0_din, "start_for_Loop_l_f1d_row_proc2_U0_din");
    sc_trace(mVcdFile, start_for_Loop_l_f1d_row_proc2_U0_full_n, "start_for_Loop_l_f1d_row_proc2_U0_full_n");
    sc_trace(mVcdFile, start_for_Loop_l_f1d_row_proc2_U0_dout, "start_for_Loop_l_f1d_row_proc2_U0_dout");
    sc_trace(mVcdFile, start_for_Loop_l_f1d_row_proc2_U0_empty_n, "start_for_Loop_l_f1d_row_proc2_U0_empty_n");
    sc_trace(mVcdFile, start_for_Loop_l_transp_mid_pr_U0_din, "start_for_Loop_l_transp_mid_pr_U0_din");
    sc_trace(mVcdFile, start_for_Loop_l_transp_mid_pr_U0_full_n, "start_for_Loop_l_transp_mid_pr_U0_full_n");
    sc_trace(mVcdFile, start_for_Loop_l_transp_mid_pr_U0_dout, "start_for_Loop_l_transp_mid_pr_U0_dout");
    sc_trace(mVcdFile, start_for_Loop_l_transp_mid_pr_U0_empty_n, "start_for_Loop_l_transp_mid_pr_U0_empty_n");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_start_full_n, "Loop_l_transp_mid_pr_U0_start_full_n");
    sc_trace(mVcdFile, Loop_l_transp_mid_pr_U0_start_write, "Loop_l_transp_mid_pr_U0_start_write");
    sc_trace(mVcdFile, start_for_Loop_l_transp_out_pr_U0_din, "start_for_Loop_l_transp_out_pr_U0_din");
    sc_trace(mVcdFile, start_for_Loop_l_transp_out_pr_U0_full_n, "start_for_Loop_l_transp_out_pr_U0_full_n");
    sc_trace(mVcdFile, start_for_Loop_l_transp_out_pr_U0_dout, "start_for_Loop_l_transp_out_pr_U0_dout");
    sc_trace(mVcdFile, start_for_Loop_l_transp_out_pr_U0_empty_n, "start_for_Loop_l_transp_out_pr_U0_empty_n");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_start_full_n, "Loop_l_transp_out_pr_U0_start_full_n");
    sc_trace(mVcdFile, Loop_l_transp_out_pr_U0_start_write, "Loop_l_transp_out_pr_U0_start_write");
    sc_trace(mVcdFile, start_for_Loop_l_wr_xk_proc29_U0_din, "start_for_Loop_l_wr_xk_proc29_U0_din");
    sc_trace(mVcdFile, start_for_Loop_l_wr_xk_proc29_U0_full_n, "start_for_Loop_l_wr_xk_proc29_U0_full_n");
    sc_trace(mVcdFile, start_for_Loop_l_wr_xk_proc29_U0_dout, "start_for_Loop_l_wr_xk_proc29_U0_dout");
    sc_trace(mVcdFile, start_for_Loop_l_wr_xk_proc29_U0_empty_n, "start_for_Loop_l_wr_xk_proc29_U0_empty_n");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_start_full_n, "Loop_l_wr_xk_proc29_U0_start_full_n");
    sc_trace(mVcdFile, Loop_l_wr_xk_proc29_U0_start_write, "Loop_l_wr_xk_proc29_U0_start_write");
#endif

    }
    mHdltvinHandle.open("fft2d_top.hdltvin.dat");
    mHdltvoutHandle.open("fft2d_top.hdltvout.dat");
}

fft2d_top::~fft2d_top() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete arr1_U;
    delete arr0_U;
    delete Loop_l_rd_xn_proc23_U0;
    delete Loop_l_f1d_row_proc2_U0;
    delete Loop_l_transp_mid_pr_U0;
    delete Loop_l_f1d_col_proc2_U0;
    delete Loop_l_transp_out_pr_U0;
    delete Loop_l_wr_o_fifo_pro_U0;
    delete Loop_l_wr_xk_proc29_U0;
    delete xn_fifo_V_U;
    delete xk_mid_row_fifo_V_U;
    delete xk_mid_col_fifo_V_U;
    delete xk_fifo_V_U;
    delete start_for_Loop_l_f1d_row_proc2_U0_U;
    delete start_for_Loop_l_transp_mid_pr_U0_U;
    delete start_for_Loop_l_transp_out_pr_U0_U;
    delete start_for_Loop_l_wr_xk_proc29_U0_U;
}

void fft2d_top::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_logic_1;
}

void fft2d_top::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv64_0;
}

void fft2d_top::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_0;
}

void fft2d_top::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv10_0;
}

void fft2d_top::thread_Loop_l_f1d_col_proc2_U0_ap_continue() {
    Loop_l_f1d_col_proc2_U0_ap_continue = ap_const_logic_1;
}

void fft2d_top::thread_Loop_l_f1d_col_proc2_U0_ap_start() {
    Loop_l_f1d_col_proc2_U0_ap_start = arr0_t_empty_n.read();
}

void fft2d_top::thread_Loop_l_f1d_row_proc2_U0_ap_continue() {
    Loop_l_f1d_row_proc2_U0_ap_continue = ap_const_logic_1;
}

void fft2d_top::thread_Loop_l_f1d_row_proc2_U0_ap_start() {
    Loop_l_f1d_row_proc2_U0_ap_start = start_for_Loop_l_f1d_row_proc2_U0_empty_n.read();
}

void fft2d_top::thread_Loop_l_rd_xn_proc23_U0_ap_continue() {
    Loop_l_rd_xn_proc23_U0_ap_continue = ap_const_logic_1;
}

void fft2d_top::thread_Loop_l_rd_xn_proc23_U0_ap_start() {
    Loop_l_rd_xn_proc23_U0_ap_start = ap_const_logic_1;
}

void fft2d_top::thread_Loop_l_rd_xn_proc23_U0_xn_TLAST() {
    Loop_l_rd_xn_proc23_U0_xn_TLAST =  (sc_lv<1>) (xn_TLAST.read());
}

void fft2d_top::thread_Loop_l_transp_mid_pr_U0_ap_continue() {
    Loop_l_transp_mid_pr_U0_ap_continue = arr0_i_full_n.read();
}

void fft2d_top::thread_Loop_l_transp_mid_pr_U0_ap_start() {
    Loop_l_transp_mid_pr_U0_ap_start = start_for_Loop_l_transp_mid_pr_U0_empty_n.read();
}

void fft2d_top::thread_Loop_l_transp_mid_pr_U0_arr0_full_n() {
    Loop_l_transp_mid_pr_U0_arr0_full_n = arr0_i_full_n.read();
}

void fft2d_top::thread_Loop_l_transp_mid_pr_U0_start_full_n() {
    Loop_l_transp_mid_pr_U0_start_full_n = ap_const_logic_1;
}

void fft2d_top::thread_Loop_l_transp_mid_pr_U0_start_write() {
    Loop_l_transp_mid_pr_U0_start_write = ap_const_logic_0;
}

void fft2d_top::thread_Loop_l_transp_out_pr_U0_ap_continue() {
    Loop_l_transp_out_pr_U0_ap_continue = arr1_i_full_n.read();
}

void fft2d_top::thread_Loop_l_transp_out_pr_U0_ap_start() {
    Loop_l_transp_out_pr_U0_ap_start = start_for_Loop_l_transp_out_pr_U0_empty_n.read();
}

void fft2d_top::thread_Loop_l_transp_out_pr_U0_arr1_full_n() {
    Loop_l_transp_out_pr_U0_arr1_full_n = arr1_i_full_n.read();
}

void fft2d_top::thread_Loop_l_transp_out_pr_U0_start_full_n() {
    Loop_l_transp_out_pr_U0_start_full_n = ap_const_logic_1;
}

void fft2d_top::thread_Loop_l_transp_out_pr_U0_start_write() {
    Loop_l_transp_out_pr_U0_start_write = ap_const_logic_0;
}

void fft2d_top::thread_Loop_l_wr_o_fifo_pro_U0_ap_continue() {
    Loop_l_wr_o_fifo_pro_U0_ap_continue = ap_const_logic_1;
}

void fft2d_top::thread_Loop_l_wr_o_fifo_pro_U0_ap_start() {
    Loop_l_wr_o_fifo_pro_U0_ap_start = arr1_t_empty_n.read();
}

void fft2d_top::thread_Loop_l_wr_xk_proc29_U0_ap_continue() {
    Loop_l_wr_xk_proc29_U0_ap_continue = ap_const_logic_1;
}

void fft2d_top::thread_Loop_l_wr_xk_proc29_U0_ap_start() {
    Loop_l_wr_xk_proc29_U0_ap_start = start_for_Loop_l_wr_xk_proc29_U0_empty_n.read();
}

void fft2d_top::thread_Loop_l_wr_xk_proc29_U0_start_full_n() {
    Loop_l_wr_xk_proc29_U0_start_full_n = ap_const_logic_1;
}

void fft2d_top::thread_Loop_l_wr_xk_proc29_U0_start_write() {
    Loop_l_wr_xk_proc29_U0_start_write = ap_const_logic_0;
}

void fft2d_top::thread_ap_channel_done_arr0() {
    ap_channel_done_arr0 = Loop_l_transp_mid_pr_U0_ap_done.read();
}

void fft2d_top::thread_ap_channel_done_arr1() {
    ap_channel_done_arr1 = Loop_l_transp_out_pr_U0_ap_done.read();
}

void fft2d_top::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void fft2d_top::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void fft2d_top::thread_arr0_t_d0() {
    arr0_t_d0 = ap_const_lv64_0;
}

void fft2d_top::thread_arr0_t_we0() {
    arr0_t_we0 = ap_const_logic_0;
}

void fft2d_top::thread_arr1_t_d0() {
    arr1_t_d0 = ap_const_lv64_0;
}

void fft2d_top::thread_arr1_t_we0() {
    arr1_t_we0 = ap_const_logic_0;
}

void fft2d_top::thread_start_for_Loop_l_f1d_row_proc2_U0_din() {
    start_for_Loop_l_f1d_row_proc2_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void fft2d_top::thread_start_for_Loop_l_transp_mid_pr_U0_din() {
    start_for_Loop_l_transp_mid_pr_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void fft2d_top::thread_start_for_Loop_l_transp_out_pr_U0_din() {
    start_for_Loop_l_transp_out_pr_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void fft2d_top::thread_start_for_Loop_l_wr_xk_proc29_U0_din() {
    start_for_Loop_l_wr_xk_proc29_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void fft2d_top::thread_xk_TDATA() {
    xk_TDATA = Loop_l_wr_xk_proc29_U0_xk_TDATA.read();
}

void fft2d_top::thread_xk_TLAST() {
    xk_TLAST =  (sc_logic) (Loop_l_wr_xk_proc29_U0_xk_TLAST.read()[0]);
}

void fft2d_top::thread_xk_TVALID() {
    xk_TVALID = Loop_l_wr_xk_proc29_U0_xk_TVALID.read();
}

void fft2d_top::thread_xn_TREADY() {
    xn_TREADY = Loop_l_rd_xn_proc23_U0_xn_TREADY.read();
}

void fft2d_top::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xn_TDATA\" :  \"" << xn_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xn_TLAST\" :  \"" << xn_TLAST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"xk_TDATA\" :  \"" << xk_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"xk_TLAST\" :  \"" << xk_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xn_TVALID\" :  \"" << xn_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"xn_TREADY\" :  \"" << xn_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"xk_TVALID\" :  \"" << xk_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xk_TREADY\" :  \"" << xk_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

