// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _fft2d_top_HH_
#define _fft2d_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Loop_l_rd_xn_proc23.h"
#include "Loop_l_f1d_row_proc2.h"
#include "Loop_l_transp_mid_pr.h"
#include "Loop_l_f1d_col_proc2.h"
#include "Loop_l_transp_out_pr.h"
#include "Loop_l_wr_o_fifo_pro.h"
#include "Loop_l_wr_xk_proc29.h"
#include "fft2d_top_arr1.h"
#include "fifo_w64_d32_A_x2.h"
#include "start_for_Loop_l_f1d_row_proc2_U0.h"
#include "start_for_Loop_l_transp_mid_pr_U0.h"
#include "start_for_Loop_l_transp_out_pr_U0.h"
#include "start_for_Loop_l_wr_xk_proc29_U0.h"

namespace ap_rtl {

struct fft2d_top : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<64> > xn_TDATA;
    sc_in< sc_logic > xn_TLAST;
    sc_out< sc_lv<64> > xk_TDATA;
    sc_out< sc_logic > xk_TLAST;
    sc_in< sc_logic > xn_TVALID;
    sc_out< sc_logic > xn_TREADY;
    sc_out< sc_logic > xk_TVALID;
    sc_in< sc_logic > xk_TREADY;
    sc_signal< sc_logic > ap_var_for_const3;
    sc_signal< sc_lv<64> > ap_var_for_const2;
    sc_signal< sc_logic > ap_var_for_const1;
    sc_signal< sc_lv<10> > ap_var_for_const0;


    // Module declarations
    fft2d_top(sc_module_name name);
    SC_HAS_PROCESS(fft2d_top);

    ~fft2d_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    fft2d_top_arr1* arr1_U;
    fft2d_top_arr1* arr0_U;
    Loop_l_rd_xn_proc23* Loop_l_rd_xn_proc23_U0;
    Loop_l_f1d_row_proc2* Loop_l_f1d_row_proc2_U0;
    Loop_l_transp_mid_pr* Loop_l_transp_mid_pr_U0;
    Loop_l_f1d_col_proc2* Loop_l_f1d_col_proc2_U0;
    Loop_l_transp_out_pr* Loop_l_transp_out_pr_U0;
    Loop_l_wr_o_fifo_pro* Loop_l_wr_o_fifo_pro_U0;
    Loop_l_wr_xk_proc29* Loop_l_wr_xk_proc29_U0;
    fifo_w64_d32_A_x2* xn_fifo_V_U;
    fifo_w64_d32_A_x2* xk_mid_row_fifo_V_U;
    fifo_w64_d32_A_x2* xk_mid_col_fifo_V_U;
    fifo_w64_d32_A_x2* xk_fifo_V_U;
    start_for_Loop_l_f1d_row_proc2_U0* start_for_Loop_l_f1d_row_proc2_U0_U;
    start_for_Loop_l_transp_mid_pr_U0* start_for_Loop_l_transp_mid_pr_U0_U;
    start_for_Loop_l_transp_out_pr_U0* start_for_Loop_l_transp_out_pr_U0_U;
    start_for_Loop_l_wr_xk_proc29_U0* start_for_Loop_l_wr_xk_proc29_U0_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<64> > arr1_i_q0;
    sc_signal< sc_lv<64> > arr1_t_q0;
    sc_signal< sc_lv<64> > arr0_i_q0;
    sc_signal< sc_lv<64> > arr0_t_q0;
    sc_signal< sc_logic > Loop_l_rd_xn_proc23_U0_ap_start;
    sc_signal< sc_logic > Loop_l_rd_xn_proc23_U0_ap_done;
    sc_signal< sc_logic > Loop_l_rd_xn_proc23_U0_ap_continue;
    sc_signal< sc_logic > Loop_l_rd_xn_proc23_U0_ap_idle;
    sc_signal< sc_logic > Loop_l_rd_xn_proc23_U0_ap_ready;
    sc_signal< sc_logic > Loop_l_rd_xn_proc23_U0_start_out;
    sc_signal< sc_logic > Loop_l_rd_xn_proc23_U0_start_write;
    sc_signal< sc_logic > Loop_l_rd_xn_proc23_U0_xn_TREADY;
    sc_signal< sc_lv<1> > Loop_l_rd_xn_proc23_U0_xn_TLAST;
    sc_signal< sc_lv<64> > Loop_l_rd_xn_proc23_U0_xn_fifo_V_din;
    sc_signal< sc_logic > Loop_l_rd_xn_proc23_U0_xn_fifo_V_write;
    sc_signal< sc_logic > Loop_l_f1d_row_proc2_U0_ap_start;
    sc_signal< sc_logic > Loop_l_f1d_row_proc2_U0_ap_done;
    sc_signal< sc_logic > Loop_l_f1d_row_proc2_U0_ap_continue;
    sc_signal< sc_logic > Loop_l_f1d_row_proc2_U0_ap_idle;
    sc_signal< sc_logic > Loop_l_f1d_row_proc2_U0_ap_ready;
    sc_signal< sc_logic > Loop_l_f1d_row_proc2_U0_start_out;
    sc_signal< sc_logic > Loop_l_f1d_row_proc2_U0_start_write;
    sc_signal< sc_lv<64> > Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_din;
    sc_signal< sc_logic > Loop_l_f1d_row_proc2_U0_xk_mid_row_fifo_V_write;
    sc_signal< sc_logic > Loop_l_f1d_row_proc2_U0_xn_fifo_V_read;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_ap_start;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_ap_done;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_ap_continue;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_ap_idle;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_ap_ready;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_xk_mid_row_fifo_V_read;
    sc_signal< sc_lv<10> > Loop_l_transp_mid_pr_U0_arr0_address1;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_arr0_ce1;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_arr0_we1;
    sc_signal< sc_lv<64> > Loop_l_transp_mid_pr_U0_arr0_d1;
    sc_signal< sc_logic > ap_channel_done_arr0;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_arr0_full_n;
    sc_signal< sc_logic > Loop_l_f1d_col_proc2_U0_ap_start;
    sc_signal< sc_logic > Loop_l_f1d_col_proc2_U0_ap_done;
    sc_signal< sc_logic > Loop_l_f1d_col_proc2_U0_ap_continue;
    sc_signal< sc_logic > Loop_l_f1d_col_proc2_U0_ap_idle;
    sc_signal< sc_logic > Loop_l_f1d_col_proc2_U0_ap_ready;
    sc_signal< sc_logic > Loop_l_f1d_col_proc2_U0_start_out;
    sc_signal< sc_logic > Loop_l_f1d_col_proc2_U0_start_write;
    sc_signal< sc_lv<64> > Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_din;
    sc_signal< sc_logic > Loop_l_f1d_col_proc2_U0_xk_mid_col_fifo_V_write;
    sc_signal< sc_lv<10> > Loop_l_f1d_col_proc2_U0_arr0_address0;
    sc_signal< sc_logic > Loop_l_f1d_col_proc2_U0_arr0_ce0;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_ap_start;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_ap_done;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_ap_continue;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_ap_idle;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_ap_ready;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_xk_mid_col_fifo_V_read;
    sc_signal< sc_lv<10> > Loop_l_transp_out_pr_U0_arr1_address1;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_arr1_ce1;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_arr1_we1;
    sc_signal< sc_lv<64> > Loop_l_transp_out_pr_U0_arr1_d1;
    sc_signal< sc_logic > ap_channel_done_arr1;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_arr1_full_n;
    sc_signal< sc_logic > Loop_l_wr_o_fifo_pro_U0_ap_start;
    sc_signal< sc_logic > Loop_l_wr_o_fifo_pro_U0_ap_done;
    sc_signal< sc_logic > Loop_l_wr_o_fifo_pro_U0_ap_continue;
    sc_signal< sc_logic > Loop_l_wr_o_fifo_pro_U0_ap_idle;
    sc_signal< sc_logic > Loop_l_wr_o_fifo_pro_U0_ap_ready;
    sc_signal< sc_logic > Loop_l_wr_o_fifo_pro_U0_start_out;
    sc_signal< sc_logic > Loop_l_wr_o_fifo_pro_U0_start_write;
    sc_signal< sc_lv<10> > Loop_l_wr_o_fifo_pro_U0_arr1_address0;
    sc_signal< sc_logic > Loop_l_wr_o_fifo_pro_U0_arr1_ce0;
    sc_signal< sc_lv<64> > Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_din;
    sc_signal< sc_logic > Loop_l_wr_o_fifo_pro_U0_xk_fifo_V_write;
    sc_signal< sc_logic > Loop_l_wr_xk_proc29_U0_ap_start;
    sc_signal< sc_logic > Loop_l_wr_xk_proc29_U0_ap_done;
    sc_signal< sc_logic > Loop_l_wr_xk_proc29_U0_ap_continue;
    sc_signal< sc_logic > Loop_l_wr_xk_proc29_U0_ap_idle;
    sc_signal< sc_logic > Loop_l_wr_xk_proc29_U0_ap_ready;
    sc_signal< sc_logic > Loop_l_wr_xk_proc29_U0_xk_fifo_V_read;
    sc_signal< sc_lv<64> > Loop_l_wr_xk_proc29_U0_xk_TDATA;
    sc_signal< sc_logic > Loop_l_wr_xk_proc29_U0_xk_TVALID;
    sc_signal< sc_lv<1> > Loop_l_wr_xk_proc29_U0_xk_TLAST;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > arr0_i_full_n;
    sc_signal< sc_logic > arr0_t_empty_n;
    sc_signal< sc_lv<64> > arr0_t_d0;
    sc_signal< sc_logic > arr0_t_we0;
    sc_signal< sc_logic > arr1_i_full_n;
    sc_signal< sc_logic > arr1_t_empty_n;
    sc_signal< sc_lv<64> > arr1_t_d0;
    sc_signal< sc_logic > arr1_t_we0;
    sc_signal< sc_logic > xn_fifo_V_full_n;
    sc_signal< sc_lv<64> > xn_fifo_V_dout;
    sc_signal< sc_logic > xn_fifo_V_empty_n;
    sc_signal< sc_logic > xk_mid_row_fifo_V_full_n;
    sc_signal< sc_lv<64> > xk_mid_row_fifo_V_dout;
    sc_signal< sc_logic > xk_mid_row_fifo_V_empty_n;
    sc_signal< sc_logic > xk_mid_col_fifo_V_full_n;
    sc_signal< sc_lv<64> > xk_mid_col_fifo_V_dout;
    sc_signal< sc_logic > xk_mid_col_fifo_V_empty_n;
    sc_signal< sc_logic > xk_fifo_V_full_n;
    sc_signal< sc_lv<64> > xk_fifo_V_dout;
    sc_signal< sc_logic > xk_fifo_V_empty_n;
    sc_signal< sc_lv<1> > start_for_Loop_l_f1d_row_proc2_U0_din;
    sc_signal< sc_logic > start_for_Loop_l_f1d_row_proc2_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Loop_l_f1d_row_proc2_U0_dout;
    sc_signal< sc_logic > start_for_Loop_l_f1d_row_proc2_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Loop_l_transp_mid_pr_U0_din;
    sc_signal< sc_logic > start_for_Loop_l_transp_mid_pr_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Loop_l_transp_mid_pr_U0_dout;
    sc_signal< sc_logic > start_for_Loop_l_transp_mid_pr_U0_empty_n;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_start_full_n;
    sc_signal< sc_logic > Loop_l_transp_mid_pr_U0_start_write;
    sc_signal< sc_lv<1> > start_for_Loop_l_transp_out_pr_U0_din;
    sc_signal< sc_logic > start_for_Loop_l_transp_out_pr_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Loop_l_transp_out_pr_U0_dout;
    sc_signal< sc_logic > start_for_Loop_l_transp_out_pr_U0_empty_n;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_start_full_n;
    sc_signal< sc_logic > Loop_l_transp_out_pr_U0_start_write;
    sc_signal< sc_lv<1> > start_for_Loop_l_wr_xk_proc29_U0_din;
    sc_signal< sc_logic > start_for_Loop_l_wr_xk_proc29_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Loop_l_wr_xk_proc29_U0_dout;
    sc_signal< sc_logic > start_for_Loop_l_wr_xk_proc29_U0_empty_n;
    sc_signal< sc_logic > Loop_l_wr_xk_proc29_U0_start_full_n;
    sc_signal< sc_logic > Loop_l_wr_xk_proc29_U0_start_write;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<64> ap_const_lv64_1;
    // Thread declarations
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const0();
    void thread_Loop_l_f1d_col_proc2_U0_ap_continue();
    void thread_Loop_l_f1d_col_proc2_U0_ap_start();
    void thread_Loop_l_f1d_row_proc2_U0_ap_continue();
    void thread_Loop_l_f1d_row_proc2_U0_ap_start();
    void thread_Loop_l_rd_xn_proc23_U0_ap_continue();
    void thread_Loop_l_rd_xn_proc23_U0_ap_start();
    void thread_Loop_l_rd_xn_proc23_U0_xn_TLAST();
    void thread_Loop_l_transp_mid_pr_U0_ap_continue();
    void thread_Loop_l_transp_mid_pr_U0_ap_start();
    void thread_Loop_l_transp_mid_pr_U0_arr0_full_n();
    void thread_Loop_l_transp_mid_pr_U0_start_full_n();
    void thread_Loop_l_transp_mid_pr_U0_start_write();
    void thread_Loop_l_transp_out_pr_U0_ap_continue();
    void thread_Loop_l_transp_out_pr_U0_ap_start();
    void thread_Loop_l_transp_out_pr_U0_arr1_full_n();
    void thread_Loop_l_transp_out_pr_U0_start_full_n();
    void thread_Loop_l_transp_out_pr_U0_start_write();
    void thread_Loop_l_wr_o_fifo_pro_U0_ap_continue();
    void thread_Loop_l_wr_o_fifo_pro_U0_ap_start();
    void thread_Loop_l_wr_xk_proc29_U0_ap_continue();
    void thread_Loop_l_wr_xk_proc29_U0_ap_start();
    void thread_Loop_l_wr_xk_proc29_U0_start_full_n();
    void thread_Loop_l_wr_xk_proc29_U0_start_write();
    void thread_ap_channel_done_arr0();
    void thread_ap_channel_done_arr1();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_continue();
    void thread_arr0_t_d0();
    void thread_arr0_t_we0();
    void thread_arr1_t_d0();
    void thread_arr1_t_we0();
    void thread_start_for_Loop_l_f1d_row_proc2_U0_din();
    void thread_start_for_Loop_l_transp_mid_pr_U0_din();
    void thread_start_for_Loop_l_transp_out_pr_U0_din();
    void thread_start_for_Loop_l_wr_xk_proc29_U0_din();
    void thread_xk_TDATA();
    void thread_xk_TLAST();
    void thread_xk_TVALID();
    void thread_xn_TREADY();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
