-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Loop_l_f1d_row_proc2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    xk_mid_row_fifo_V_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    xk_mid_row_fifo_V_full_n : IN STD_LOGIC;
    xk_mid_row_fifo_V_write : OUT STD_LOGIC;
    xn_fifo_V_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    xn_fifo_V_empty_n : IN STD_LOGIC;
    xn_fifo_V_read : OUT STD_LOGIC );
end;


architecture behav of Loop_l_f1d_row_proc2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal xn_fifo_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln130_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_138_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_reg_165 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal j_fu_150_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal xn_mid_row_fifo_V_full_n : STD_LOGIC;
    signal xn_mid_row_fifo_V_write : STD_LOGIC;
    signal ap_block_state3 : BOOLEAN;
    signal grp_fft1d_1_fu_125_in_V_read : STD_LOGIC;
    signal grp_fft1d_1_fu_125_out_V_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fft1d_1_fu_125_out_V_write : STD_LOGIC;
    signal grp_fft1d_1_fu_125_ap_start : STD_LOGIC;
    signal grp_fft1d_1_fu_125_ap_done : STD_LOGIC;
    signal grp_fft1d_1_fu_125_ap_ready : STD_LOGIC;
    signal grp_fft1d_1_fu_125_ap_idle : STD_LOGIC;
    signal grp_fft1d_1_fu_125_ap_continue : STD_LOGIC;
    signal i1_0_reg_103 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_sync_grp_fft1d_1_fu_125_ap_ready : STD_LOGIC;
    signal ap_sync_grp_fft1d_1_fu_125_ap_done : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal j_0_reg_114 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln128_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fft1d_1_fu_125_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state3_ignore_call0 : BOOLEAN;
    signal ap_sync_reg_grp_fft1d_1_fu_125_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_fft1d_1_fu_125_ap_done : STD_LOGIC := '0';
    signal xn_mid_row_fifo_V_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal xn_mid_row_fifo_V_empty_n : STD_LOGIC;
    signal xn_mid_row_fifo_V_read : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);

    component fft1d_1 IS
    port (
        in_V_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        in_V_empty_n : IN STD_LOGIC;
        in_V_read : OUT STD_LOGIC;
        out_V_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_V_full_n : IN STD_LOGIC;
        out_V_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component fifo_w64_d32_A_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    grp_fft1d_1_fu_125 : component fft1d_1
    port map (
        in_V_dout => xn_mid_row_fifo_V_dout,
        in_V_empty_n => xn_mid_row_fifo_V_empty_n,
        in_V_read => grp_fft1d_1_fu_125_in_V_read,
        out_V_din => grp_fft1d_1_fu_125_out_V_din,
        out_V_full_n => xk_mid_row_fifo_V_full_n,
        out_V_write => grp_fft1d_1_fu_125_out_V_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fft1d_1_fu_125_ap_start,
        ap_done => grp_fft1d_1_fu_125_ap_done,
        ap_ready => grp_fft1d_1_fu_125_ap_ready,
        ap_idle => grp_fft1d_1_fu_125_ap_idle,
        ap_continue => grp_fft1d_1_fu_125_ap_continue);

    xn_mid_row_fifo_V_fifo_U : component fifo_w64_d32_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xn_fifo_V_dout,
        if_full_n => xn_mid_row_fifo_V_full_n,
        if_write => xn_mid_row_fifo_V_write,
        if_dout => xn_mid_row_fifo_V_dout,
        if_empty_n => xn_mid_row_fifo_V_empty_n,
        if_read => xn_mid_row_fifo_V_read);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln128_fu_132_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_fft1d_1_fu_125_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_fft1d_1_fu_125_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4_on_subcall_done))) then 
                    ap_sync_reg_grp_fft1d_1_fu_125_ap_done <= ap_const_logic_0;
                elsif ((grp_fft1d_1_fu_125_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_fft1d_1_fu_125_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_fft1d_1_fu_125_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_fft1d_1_fu_125_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4_on_subcall_done))) then 
                    ap_sync_reg_grp_fft1d_1_fu_125_ap_ready <= ap_const_logic_0;
                elsif ((grp_fft1d_1_fu_125_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_fft1d_1_fu_125_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_fft1d_1_fu_125_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft1d_1_fu_125_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_sync_grp_fft1d_1_fu_125_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not((((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_mid_row_fifo_V_full_n = ap_const_logic_0)) or ((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_fifo_V_empty_n = ap_const_logic_0)))) and (icmp_ln130_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
                    grp_fft1d_1_fu_125_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft1d_1_fu_125_ap_ready = ap_const_logic_1)) then 
                    grp_fft1d_1_fu_125_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i1_0_reg_103_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i1_0_reg_103 <= ap_const_lv6_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4_on_subcall_done))) then 
                i1_0_reg_103 <= i_reg_165;
            end if; 
        end if;
    end process;

    j_0_reg_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_mid_row_fifo_V_full_n = ap_const_logic_0)) or ((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_fifo_V_empty_n = ap_const_logic_0)))) and (icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                j_0_reg_114 <= j_fu_150_p2;
            elsif (((icmp_ln128_fu_132_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_114 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_165 <= i_fu_138_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, xn_fifo_V_empty_n, ap_CS_fsm_state3, icmp_ln130_fu_144_p2, ap_CS_fsm_state2, xn_mid_row_fifo_V_full_n, ap_CS_fsm_state4, ap_block_state4_on_subcall_done, icmp_ln128_fu_132_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln128_fu_132_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not((((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_mid_row_fifo_V_full_n = ap_const_logic_0)) or ((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_fifo_V_empty_n = ap_const_logic_0)))) and (icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not((((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_mid_row_fifo_V_full_n = ap_const_logic_0)) or ((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_fifo_V_empty_n = ap_const_logic_0)))) and (icmp_ln130_fu_144_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state3_assign_proc : process(xn_fifo_V_empty_n, icmp_ln130_fu_144_p2, xn_mid_row_fifo_V_full_n)
    begin
                ap_block_state3 <= (((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_mid_row_fifo_V_full_n = ap_const_logic_0)) or ((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_fifo_V_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state3_ignore_call0_assign_proc : process(xn_fifo_V_empty_n, icmp_ln130_fu_144_p2, xn_mid_row_fifo_V_full_n)
    begin
                ap_block_state3_ignore_call0 <= (((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_mid_row_fifo_V_full_n = ap_const_logic_0)) or ((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_fifo_V_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(ap_sync_grp_fft1d_1_fu_125_ap_ready, ap_sync_grp_fft1d_1_fu_125_ap_done)
    begin
                ap_block_state4_on_subcall_done <= ((ap_sync_grp_fft1d_1_fu_125_ap_ready and ap_sync_grp_fft1d_1_fu_125_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln128_fu_132_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln128_fu_132_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    ap_sync_grp_fft1d_1_fu_125_ap_done <= (grp_fft1d_1_fu_125_ap_done or ap_sync_reg_grp_fft1d_1_fu_125_ap_done);
    ap_sync_grp_fft1d_1_fu_125_ap_ready <= (grp_fft1d_1_fu_125_ap_ready or ap_sync_reg_grp_fft1d_1_fu_125_ap_ready);

    grp_fft1d_1_fu_125_ap_continue_assign_proc : process(ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4_on_subcall_done))) then 
            grp_fft1d_1_fu_125_ap_continue <= ap_const_logic_1;
        else 
            grp_fft1d_1_fu_125_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_fft1d_1_fu_125_ap_start <= grp_fft1d_1_fu_125_ap_start_reg;
    i_fu_138_p2 <= std_logic_vector(unsigned(i1_0_reg_103) + unsigned(ap_const_lv6_1));
    icmp_ln128_fu_132_p2 <= "1" when (i1_0_reg_103 = ap_const_lv6_20) else "0";
    icmp_ln130_fu_144_p2 <= "1" when (j_0_reg_114 = ap_const_lv6_20) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln128_fu_132_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln128_fu_132_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    j_fu_150_p2 <= std_logic_vector(unsigned(j_0_reg_114) + unsigned(ap_const_lv6_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    xk_mid_row_fifo_V_din <= grp_fft1d_1_fu_125_out_V_din;

    xk_mid_row_fifo_V_write_assign_proc : process(grp_fft1d_1_fu_125_out_V_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            xk_mid_row_fifo_V_write <= grp_fft1d_1_fu_125_out_V_write;
        else 
            xk_mid_row_fifo_V_write <= ap_const_logic_0;
        end if; 
    end process;


    xn_fifo_V_blk_n_assign_proc : process(xn_fifo_V_empty_n, ap_CS_fsm_state3, icmp_ln130_fu_144_p2)
    begin
        if (((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            xn_fifo_V_blk_n <= xn_fifo_V_empty_n;
        else 
            xn_fifo_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    xn_fifo_V_read_assign_proc : process(xn_fifo_V_empty_n, ap_CS_fsm_state3, icmp_ln130_fu_144_p2, xn_mid_row_fifo_V_full_n)
    begin
        if ((not((((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_mid_row_fifo_V_full_n = ap_const_logic_0)) or ((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_fifo_V_empty_n = ap_const_logic_0)))) and (icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            xn_fifo_V_read <= ap_const_logic_1;
        else 
            xn_fifo_V_read <= ap_const_logic_0;
        end if; 
    end process;


    xn_mid_row_fifo_V_read_assign_proc : process(grp_fft1d_1_fu_125_in_V_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            xn_mid_row_fifo_V_read <= grp_fft1d_1_fu_125_in_V_read;
        else 
            xn_mid_row_fifo_V_read <= ap_const_logic_0;
        end if; 
    end process;


    xn_mid_row_fifo_V_write_assign_proc : process(xn_fifo_V_empty_n, ap_CS_fsm_state3, icmp_ln130_fu_144_p2, xn_mid_row_fifo_V_full_n)
    begin
        if ((not((((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_mid_row_fifo_V_full_n = ap_const_logic_0)) or ((icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (xn_fifo_V_empty_n = ap_const_logic_0)))) and (icmp_ln130_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            xn_mid_row_fifo_V_write <= ap_const_logic_1;
        else 
            xn_mid_row_fifo_V_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
